// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDaemonURL() {
  return window['go']['main']['App']['GetDaemonURL']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}
